name: astro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17
  file_picker: ^5.0.1
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.4.5
  flutter_chat_ui: ^1.6.4
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  get: 4.6.5
  google_fonts: null
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  introduction_screen: ^3.0.2
  mime: ^1.0.2
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  rating_dialog: ^2.0.4
  readmore: ^2.2.0
  skeletons: ^0.0.3
  smart_auth: ^1.0.5
  sms_autofill: ^2.2.0
  sticky_headers: ^0.3.0+2
  textfield_search: ^0.10.0
  timer_count_down: ^2.2.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - messages.json
